<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <!-- x-->
    <xacro:property name="base_width" value="0.4" />
    <!-- y-->
    <xacro:property name="base_height" value="0.2" />
    <!--z-->
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <xacro:macro name="wheel_link" params="prefix">
        <link name ="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="1.5708 0 0" />
                <material name = "red" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                    <origin xyz="0 0 0" rpy="0 0 0" />
                </geometry>
            </collision>
            <xacro:wheel_inertia m="2.0" o_xyz="0 0 0" o_rpy="1.5708 0 0" r="${wheel_radius}" h="${wheel_length}" />
        </link>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <!-- Metric system is used in urdf ros -->
                <box size="${base_length} ${base_width} ${base_height}"/>
                <!--  length , width , height in meters-->
            </geometry>            <!-- rpy is roll,pitch,yaw -->
            <origin xyz="0 0 0.1" rpy="0 0 0" />
            <material name = "blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" o_xyz="0 0 0.1" o_rpy="0 0 0" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </link>
    <link name="footprint">
    </link>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <link name="sphere_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.05" />
                <origin xyz="0 0 0" rpy="0 0 0" />
            </geometry>
        </collision>
        <xacro:sphere_inertia m="1.0" o_xyz="0 0 0" o_rpy="0 0 0" r="0.05"/>
    </link>


    <joint name="base_joint" type="fixed">
        <parent link="footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_sphere_joint" type="continuous">
        <parent link="base_link" />
        <child link="sphere_link" />
        <origin xyz="0.2 0 -0.05" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_right_wheel" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-base_width / 2.0 - wheel_length/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${base_width / 2.0 + wheel_length/2} 0" rpy="0 0 0" />
        <!-- 0.15 is the length 0.225 is height 0 is XYZ respective to height of base -->
        <axis xyz="0 1 0"/>
    </joint>
</robot>